source 'https://rubygems.org'

ruby '2.1.5'

gem 'rails', '4.1.8'

gem 'rake','10.4.2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
#gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

gem 'high_voltage'

# angular stuff
gem 'angular-rails-templates'
gem 'ngannotate-rails'


# bundle exec rake doc:rails generates the API under doc/api.
group :doc do
	gem 'sdoc', '~> 0.4.0'
end

group :development do
	# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
	gem 'spring'

	# Dotenv allows loading of local environment variables
    gem 'dotenv-rails'
end

group :development, :test do
  gem 'rspec-rails',  '~> 3.0'
  gem 'factory_girl_rails'
end

group :test do
  gem 'shoulda-matchers'
end

# needed for heroku
group :production do
	gem 'rails_12factor'
end


# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

